services:
  nginx:
    container_name: acc2-nginx
    image: nginx
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
    networks:
      - acc2-network
    restart: 
      unless-stopped

  db:
    container_name: acc2-db
    image: postgres:17-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - acc2-network
    restart: unless-stopped

  api:
    container_name: acc2-api
    build: 
      context: ../backend
      dockerfile: Dockerfile.app
    volumes:
      - /home/acc2:/home/acc2
      - /var/log/acc2:/var/log/acc2
    environment:
      ACC2_DB_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-postgres}"
      CHARGEFW2_INSTALL_DIR: ${CHARGEFW2_INSTALL_DIR:-/ChargeFW2/build}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acc2-network
    restart: unless-stopped

  web:
    container_name: acc2-web
    build: 
      context: ../frontend
      args:
        - VITE_BASE_API_URL
    networks:
      - acc2-network
    restart: unless-stopped

networks:
  acc2-network:


volumes:
  db-data:
