name: Backend CI

on:
  push:
    branches:
      - architecture-redesign # TODO: change to main when merged to upstream
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - architecture-redesign # TODO: change to main when merged to upstream
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: pilatmartin/acc2-chargefw2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y curl python3.12-dev libpq-dev gcc
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/github/home/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH # allow poetry to be used in next step
          poetry env use python3.12
          poetry install --no-interaction --no-root
        working-directory: ./src/backend

      - name: Run tests
        run: |
          poetry run pytest ./tests
        working-directory: ./src/backend
