name: Frontend CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: ./src/frontend/acc2

      - name: Lint
        run: pnpm lint
        working-directory: ./src/frontend/acc2

      - name: Build
        run: pnpm build
        working-directory: ./src/frontend/acc2
